### ISSUE TITLE
plotflow slow in linux

### ISSUE THREAD

**Issue by econgithub** [trinker/plotflow#9]
Tyler,

I love plotflow package. It has enabled me to do many PDF-relatd work for web scraping. One thing I am challenged with, however, is its speed on linux. I am running it on a Centos 7 server and it takes about 4-5 minutes what it would otherwise take 5-7 seconds on a Mac. Specs-wise, these two machines are not vastly different from each other.

I was wondering what the reason would be and how I can make it faster.

Thank you, again, Tyler, for your good work.

**Comment by trinker** [comment]
Can you provide a minimal working example?
